[build]
  command = "npm run build"
  publish = "build"

[functions]
  # This tells Netlify where your functions are
  directory = "netlify/functions/"
  # This tells Netlify to include your data file
  included_files = ["db.json"]

# Rule for your API requests
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Rule for your React app's pages
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200