[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions/" # Tells Netlify where your functions are

# Rule for your API requests
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Rule for your React app's pages
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200